GET http://localhost:6060/users

#####

GET http://localhost:6060/users/64aebd872fa8b79a27f23ab3

#####

POST http://localhost:6060/users HTTP/1.1
Content-Type: application/json

{
"name": "Matteo",
"surname": "Di Gennaro",
"email": "mtg@gmail.com",
"birthdate": "11/09/1995",
"avatar": "avatar3.jpg"
}

#####

PATCH http://localhost:6060/users/64aebd872fa8b79a27f23ab3 HTTP/1.1
Content-Type: application/json

{
    "name": "Matteone"
}

#####

DELETE http://localhost:6060/users/64aebd872fa8b79a27f23ab3
